version: "3.1"

services:
  pg:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: rshort_link
    volumes:
      - ./.dev/postgres/01:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:5-alpine
    container_name: goal_redis
    restart: always
    volumes:
      - ./.dev/redis/01:/data
    ports:
      - 6379:6379
